export const CLARITY_LIFECYCLE_COPY = {
  consentSignIn: 'Sign in to save consent',
  consentEmail: 'An account email is required',
  consentRequired: 'Explicit consent required',
  consentError: 'Consent could not be saved',
  requestInvalid: 'Invalid Clarity request ID',
  requestConflict: 'This request ID already belongs to different answers',
  consentVersion: 'ipurpose-marketing-2026-10-04-v1',
  consentSource: 'mobile_create_account',
  consent: 'Send me occasional iPurpose emails with guidance, resources, and updates. I can unsubscribe any time.',
  neutralGreeting: 'there',
  welcomeSubject: 'Welcome to iPurpose Compass',
  welcomeBody: (firstName: string) => `Hi ${firstName}, thank you for taking the Clarity Check. Your Clarity Check results are saved in your iPurpose Compass account, and you can come back to them any time in the app. This is a one-time account message. You'll only receive marketing emails from us if you've chosen to. — The iPurpose team`,
  resultsSubject: 'Your iPurpose Clarity Check results',
  resultsIntro: (firstName: string) => `Hi ${firstName}, here are your Clarity Check results.`,
  resultsSaved: 'Your results are saved in your iPurpose Compass account.',
  resultsLink: 'View your Clarity Check results',
  summary: 'Your Summary', nextStep: 'Your Next Step', identity: 'Your Identity Type',
  score: 'Total Score',
  dimensions: ['Internal Clarity', 'Readiness for Support', 'Friction Between Insight & Action', 'Integration & Momentum'],
} as const;
